version: '3.1'

services:

  cache:
    container_name: memcached
    image: memcached:latest
    restart: always
    environment:
      TZ: "Asia/Taipei"
    ports:
      - "11211:11211"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
        reservations:
          cpus: '0.5'
          memory: 64M