version: '3.1'

services:

  shadowsocks:
    container_name: shadowsocks
    image: shadowsocks/shadowsocks-libev:latest
    restart: always
    ports:
      - 8388:8388
      - 8388:8388/udp
    environment:
      PASSWORD: Very_Strong_Password
#      METHOD: aes-256-gcm
