version: '3.3'

services:
  web:
    image: prestashop/prestashop:1.7-7.0
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini

