---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: backend
  pull: if-not-exists
  image: composer:1.9.1
  commands:
  - cp .env.example .env
  - composer install

- name: frontend
  pull: if-not-exists
  image: node:10.18.1
  commands:
  - npm i
  - npm run production
  - find . -type f -exec chmod 664 {} +
  - find . -type d -exec chmod 775 {} +
  - chmod +x artisan
  - chown -R www-data:www-data .
  - rm -rf .git
  - rm .env

- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: SSH_SERVER
    user:
      from_secret: SSH_USER
    key:
      from_secret: SSH_PRIVATE_KEY
    source: ./
    target: /var/www/drone_ci
