version: '3.1'

services:

  webserver:
    image: nginx:latest
    restart: always
    environment:
      TZ: "Asia/Taipei"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - ./snippets:/etc/nginx/snippets
