version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PPassw0rdD
