version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    ports:
      - 8080:8080