version: '3.1'

services:

  db:
    container_name: mariadb_slave
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3001 --log-slave-updates
    environment:
      MYSQL_ROOT_PASSWORD: root_PassW0rd